apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescale-main
    url: timescaledb:5432
    database: stockdb
    user: stock
    isDefault: true
    secureJsonData:
      password: stock123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
  - name: Prometheus
    type: prometheus
    uid: prometheus-main
    url: http://prometheus:9090
    access: proxy
